services:
  - type: web
    name: wallacepos
    env: node
    buildCommand: ./render-build.sh
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    nodeVersion: 16  # Specify a supported Node.js version
